"""init schema

Revision ID: bd3a595058f1
Revises: 
Create Date: 2026-04-25 14:59:40.690791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd3a595058f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False, comment='数据源标识'),
    sa.Column('source_url', sa.String(length=1024), nullable=False, comment='原文 URL'),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False, comment='正文纯文本'),
    sa.Column('category', sa.String(length=32), nullable=False, comment='学业/活动/党团/就业/其他'),
    sa.Column('publish_time', sa.DateTime(timezone=True), nullable=True, comment='原文发布时间'),
    sa.Column('content_hash', sa.String(length=64), nullable=False, comment='正文 SHA-256 用于去重'),
    sa.Column('crawled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index('idx_articles_category', 'articles', ['category'], unique=False)
    op.create_index('idx_articles_publish_time', 'articles', [sa.literal_column('publish_time DESC')], unique=False)
    op.create_index('idx_articles_source', 'articles', ['source'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('college', sa.String(length=64), nullable=True, comment='所属学院'),
    sa.Column('grade', sa.String(length=16), nullable=True, comment='年级，如 2024'),
    sa.Column('role', sa.String(length=16), nullable=True, comment='学生/教师'),
    sa.Column('subscribed_tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.create_table('chat_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('retrieved_article_ids', postgresql.ARRAY(sa.BigInteger()), nullable=False, comment='本次检索命中的文章 ID 列表'),
    sa.Column('feedback', sa.SmallInteger(), nullable=True, comment='用户反馈：-1 不满意 / 0 中性 / 1 满意'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_unread',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'article_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_unread')
    op.drop_table('chat_logs')
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_articles_source', table_name='articles')
    op.drop_index('idx_articles_publish_time', table_name='articles')
    op.drop_index('idx_articles_category', table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
